/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_edge_free: (a: number, b: number) => void;
export const __wbg_jsnode_free: (a: number, b: number) => void;
export const __wbg_taskresponse_free: (a: number, b: number) => void;
export const __wbg_wasmtaskctx_free: (a: number, b: number) => void;
export const can_run_in_wasm: (a: number, b: number) => number;
export const edge_end: (a: number) => [number, number];
export const edge_new: (a: number, b: number, c: number, d: number) => number;
export const edge_start: (a: number) => [number, number];
export const jsnode_attr: (a: number, b: number, c: number) => any;
export const jsnode_name: (a: number) => [number, number];
export const nadi_autocomplete_list: (a: number, b: number) => [number, number];
export const nadi_draw_network: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => void;
export const nadi_function_help: (a: number, b: number) => [number, number];
export const nadi_list_functions: (a: number, b: number) => [number, number];
export const run_tasks: (a: number, b: number) => [number, number];
export const taskresponse_paste: (a: number, b: number, c: number) => void;
export const wasmtaskctx_autocomplete: (a: number) => [number, number];
export const wasmtaskctx_changed: (a: number) => number;
export const wasmtaskctx_draw_on_canvas: (a: number, b: number, c: number) => any;
export const wasmtaskctx_edges: (a: number) => [number, number];
export const wasmtaskctx_load_edge_attrs: (a: number, b: number, c: number) => [number, number];
export const wasmtaskctx_load_network: (a: number, b: number, c: number) => [number, number];
export const wasmtaskctx_load_network_attrs: (a: number, b: number, c: number) => [number, number];
export const wasmtaskctx_net_attr: (a: number, b: number, c: number) => any;
export const wasmtaskctx_new: () => number;
export const wasmtaskctx_node_by_index: (a: number, b: number) => number;
export const wasmtaskctx_node_by_name: (a: number, b: number, c: number) => number;
export const wasmtaskctx_nodes: (a: number) => [number, number];
export const wasmtaskctx_reset_changed: (a: number) => void;
export const wasmtaskctx_run_tasks: (a: number, b: number, c: number) => number;
export const wasmtaskctx_tooltip: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const wasm_bindgen_85c0e06f67b82c55___convert__closures_____invoke___js_sys_4c4c80083218797f___Function_fn_wasm_bindgen_85c0e06f67b82c55___JsValue_____wasm_bindgen_85c0e06f67b82c55___sys__Undefined___js_sys_4c4c80083218797f___Function_fn_wasm_bindgen_85c0e06f67b82c55___JsValue_____wasm_bindgen_85c0e06f67b82c55___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_85c0e06f67b82c55___convert__closures_____invoke___wasm_bindgen_85c0e06f67b82c55___JsValue__core_f0fd674eaa06beef___result__Result_____wasm_bindgen_85c0e06f67b82c55___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
